name = "home"
pages_build_output_dir = "./"

# 环境配置
[env.production]
name = "home-production"
NODE_VERSION = "21.1.0"
YARN_VERSION = "1.22.0"

[env.preview]
name = "home-preview"
NODE_VERSION = "21.1.0"
YARN_VERSION = "1.22.0"